VDS-91: Fix sonarcloud issues
VirtoCommerce/vc-demo-theme-default pull request #23
Opened 2021-05-03 07:20 UTC by pushnitsa

Description: 

--

QA-test: 

Demo-test: 

Download artifact URL:

2021-05-11 13:59 UTC, trueboroda requested changes

2021-05-11 13:59 UTC, trueboroda commented on assets/js/account/account-quotes.tpl.liquid
> +    <table class="full" ng-if="$ctrl.entries.length" aria-label=" ">
aira-label should have an accessible name. Normal meaningful name.

2021-05-11 13:59 UTC, trueboroda commented on assets/js/account/account-quotes.tpl.liquid
> +                <th id="quote_number">{{ 'customer.quotes.quote_number' | t }}</th>
It is recommended to add scope attributes to <th> headers whenever possible.
<th scope="col">{{ 'customer.quotes.quote_number' | t }}</th>
<th scope="col">{{ 'customer.quotes.date' | t }}</th>
<th scope="col">{{ 'customer.quotes.status' | t }}</th>

2021-05-11 13:59 UTC, trueboroda commented on assets/js/lists/account-lists.tpl.liquid
> +            <table class="vc-product-table list-table" aria-hidden="true">
The more preferable way is to use role="presentation".

No issue will be raised on <table> used for layout purpose, i.e. when it contains a role attribute set to "presentation" or "none".

2021-05-11 13:59 UTC, trueboroda commented on templates/customers/order.liquid
> +          <th id="order_product">{{ 'customer.order.product' | t }}</th>
Use scope="col" for th

2021-05-11 13:59 UTC, trueboroda commented on templates/customers/order.liquid
> +    <table class="full" aria-hidden="true">
Use aria-label instead of aria-hidden

2021-05-11 13:59 UTC, trueboroda commented on templates/customers/quote-requests.liquid
> +        <table class="full" aria-hidden="true">
use aria-label

2021-05-11 13:59 UTC, trueboroda commented on templates/customers/quote-requests.liquid
> +                    <th id="qoute_number">{{ 'customer.quotes.quote_number' | t }}</th>
Use scope="col"

2021-05-11 13:59 UTC, trueboroda commented on templates/quote-request.liquid
> +                <table aria-hidden="true">
Use role="presentation"

2021-05-11 13:59 UTC, trueboroda commented on templates/thanks.liquid
> +    <table class="full" aria-hidden="true">
Use area-label

2021-05-11 13:59 UTC, trueboroda commented on templates/thanks.liquid
> +                <th id="order_product">{{ 'customer.order.product' | t }}</th>
Use scope="col"

2021-05-11 14:17 UTC, pushnitsa commented on assets/js/lists/account-lists.tpl.liquid
> +            <table class="vc-product-table list-table" aria-hidden="true">
In this case, sonar produces another issue :)

2021-05-11 18:41 UTC, trueboroda commented on templates/quote-request.liquid
> +                <table aria-label="Quote request">
Tabel serves for layout purposes. Maybe it is better to use aria-hidden="true" or set  role="presentation" and mark this sonar rule as "will not be fixed".

2021-05-12 08:57 UTC, trueboroda approved these changes

2021-05-12 09:05 UTC, asvishnyakov approved these changes

2021-05-13 13:12 UTC, merged